package copper

import (
	"bytes"
	"encoding/gob"
	"fmt"
)

// Complete state capture, for rewind and for replaying execution forward from
// a captured point.
//
// The 1024-instruction list is the bulk of the bytes but not the part that
// decides what happens next. That comes from the small state around it: where
// the program counter is parked inside the list, whether the copper is running
// and in which start mode, the raster line the last step was taken at, the
// write cursor, and the NR$60 hi/lo byte-pairing phase.
//
// Two of those deserve naming, because they are invisible to the guest and to
// every snapshot format:
//
//   - The write cursor. It is the FPGA's nr_copper_addr: an 11-bit BYTE
//     address, so its low bit decides whether the next NR$60 byte lands in an
//     instruction's high half or its low one. That is the whole of the
//     "pairing phase" — there is no separate latch, because NR$60 writes each
//     byte straight into its own half of the addressed word
//     (zxnext.vhd:3977-3999). Lose the cursor's low bit across a rewind and
//     every instruction after the restore is assembled half a word out.
//   - lastScanline. It is one half of a comparison: a StartOnVBL restart fires
//     when the line being stepped is below the line last stepped. Restore
//     without it and the first step after the rewind either invents a restart
//     that did not happen or misses one that did, and the list runs a frame out
//     of phase with the raster it is supposed to be painting.
//
// What is NOT here, and why:
//
//   - regs is the RegWriter, wiring to the NextReg dispatcher installed by
//     SetRegWriter at machine-build time (WireCopper, pkg/next/wire.go).
//     Capturing it would restore a function table, not a state, and a rewind
//     that silently reattached or replaced the dispatcher would change where
//     every subsequent MOVE lands. It survives a restore untouched, which is
//     what the caller that installed it expects.
//   - wrote (and executing). Both describe the Step call in progress or just
//     finished, not the device: wrote is the model's copper_dout_s sampled per
//     call, and it is regenerated by the very next Step. Capturing it would be
//     inventing a field the copper does not have. The cost of leaving it out is
//     that the first row composed after a restore may split one range it did
//     not need to, which changes no pixel.
//
// There is no horizontal position to capture. The copper's 8-pixel WAIT column
// lives in the instruction word, and the raster position it is compared against
// arrives as an argument to Step from the video timing rather than being held
// here (see WaitHThreshold), so the only raster state the copper itself owns is
// lastScanline. Storing an hcount would be inventing a field the device does
// not have.
//
// The copper has no lock of its own; like every other access to it (NextReg
// writes, Step), SaveState and LoadState belong on the emulation goroutine.

// copperState is the wire form. Every field is exported because gob only
// encodes exported fields, and every field of the running Copper is present:
// adding a field to Copper without adding it here is the failure this package's
// tests are built to catch.
type copperState struct {
	// Version is the meaning of the fields below, not the framing (the
	// machinestate container carries that). It exists because WritePtr
	// changed from a 10-bit instruction-word index to the FPGA's 11-bit
	// byte address, and gob does not police a schema: it decodes what it
	// recognises and zero-fills the rest, so a capture written under the
	// old meaning would have restored silently at half the intended
	// cursor and assembled every later instruction from the wrong
	// offset. Bump it whenever a field's meaning changes rather than its
	// name.
	Version int

	Program [MaxInstructions]uint16

	WritePtr uint16

	Mode    byte
	Pc      uint16
	Stopped bool

	// RestartPending is a mode change into 01 or 11 that the engine has not yet
	// acted on, which is the device's last_state_s comparison (copper.vhd:50,
	// :70-76) reduced to what survives between a write and the next clock. It
	// has to be captured: a restore that invents one rewinds a running list to
	// instruction 0, and a restore that loses one leaves a list that the
	// recorded machine was about to restart running on from where it stood.
	RestartPending bool

	LastScanline uint16
}

// copperStateVersion is the current meaning of copperState's fields.
// Version 1 introduced the byte-address write cursor.
// Version 2 added a LastMode byte. Version 3 replaced it with RestartPending,
// which is a change of MEANING rather than of name, and gob ignores fields it
// does not recognise, so a version 2 blob decodes cleanly against the version 3
// struct with RestartPending false and no error. Leaving the number at 2 would
// have made the two formats indistinguishable on the wire; hence 3.
//
// Versions 1 and 2 are both migrated rather than refused. See LoadState.
const copperStateVersion = 3

// StateID identifies the copper in a captured machine state.
func (c *Copper) StateID() string { return "next.copper" }

// SaveState captures the complete copper state.
func (c *Copper) SaveState() []byte {
	s := copperState{
		Program:        c.program,
		Version:        copperStateVersion,
		WritePtr:       c.writePtr,
		Mode:           byte(c.mode),
		RestartPending: c.restartPending,
		Pc:             c.pc,
		Stopped:        c.stopped,
		LastScanline:   c.lastScanline,
	}

	var buf bytes.Buffer
	if err := gob.NewEncoder(&buf).Encode(s); err != nil {
		// Encoding a fixed-size array of fixed-size values cannot fail for any
		// reason the caller could act on, and returning an error here would
		// push a dead branch into every caller. A nil blob is rejected by
		// LoadState, so even an impossible failure surfaces as a failed restore
		// rather than a silently empty copper list.
		return nil
	}
	return buf.Bytes()
}

// LoadState restores a state captured by SaveState.
//
// The whole blob is decoded before any of it is applied, so a malformed state
// leaves the copper untouched rather than half-rewound — a copper with its list
// restored but its pairing phase left in the present is exactly the corruption
// this file exists to prevent.
func (c *Copper) LoadState(b []byte) error {
	if len(b) == 0 {
		return fmt.Errorf("copper: empty state (the capture failed)")
	}
	var s copperState
	if err := gob.NewDecoder(bytes.NewReader(b)).Decode(&s); err != nil {
		return fmt.Errorf("copper: decoding state: %w", err)
	}

	if s.Version < 1 || s.Version > copperStateVersion {
		return fmt.Errorf("copper: state version %d, want 1..%d: version 0 predates the byte-address write cursor, so an older capture would restore at half its intended position, and a higher version comes from a build this one cannot read",
			s.Version, copperStateVersion)
	}

	// Neither older version can supply RestartPending: version 1 predates the
	// field and version 2's LastMode is no longer in the struct to read. False
	// is the right assumption for both, because a capture with one armed is a
	// capture taken between a mode write and the very next copper clock, which
	// is a single 28 MHz tick wide. Refusing them instead would not lose the
	// Copper's share of an old snapshot: one device's error aborts and rolls
	// back the whole machine restore, so it would lose the snapshot entirely,
	// and every rewind buffer with it. A one-clock window is the far smaller
	// error.
	restartPending := s.RestartPending
	if s.Version < 3 {
		restartPending = false
	}

	// The version says which fields exist, not that their values are possible.
	// A truncated or corrupted blob decodes to something gob is happy with and
	// this is not: a mode outside 0..3 leaves Mode() reporting a value no switch
	// handles, and a program counter past the end indexes nothing.
	if s.Mode > byte(StartOnVBL) {
		return fmt.Errorf("copper: state has mode %d, want 0..%d", s.Mode, StartOnVBL)
	}
	if int(s.Pc) >= MaxInstructions {
		return fmt.Errorf("copper: state has pc %d, want below %d", s.Pc, MaxInstructions)
	}

	c.program = s.Program
	c.writePtr = s.WritePtr
	c.mode = StartMode(s.Mode)
	c.restartPending = restartPending
	c.pc = s.Pc
	c.stopped = s.Stopped
	c.lastScanline = s.LastScanline
	return nil
}
