package audio

import (
	"encoding/binary"
	"fmt"
	"os"
	"sync"

	"github.com/hajimehoshi/oto/v2"
)

// AYSource is the minimal interface that the audio system needs from an AY
// sound chip implementation. It is satisfied by *ay.AY but kept as an
// interface here so the audio package does not need to import the ay package
// (which would create a dependency cycle through the ULA).
type AYSource interface {
	MixInto(buf []int16)
}

const (
	// Audio parameters
	SampleRate   = 44100
	ChannelCount = 2    // Stereo
	BitDepth     = 16   // 16-bit
	BufferSize   = 1024 // oto buffer size in samples — small enough that Read() runs ~43 times/sec, keeping playback latency low

	// SamplesPerFrame is the number of mono beeper samples one
	// emulator frame produces at SampleRate / 50Hz. The ULA pushes
	// exactly this many samples to the audio system per frame.
	SamplesPerFrame = SampleRate / 50

	// queueCapacity is the ring buffer size in mono samples — about
	// 12 frames at 50Hz (~240 ms). Wide enough to absorb scheduler
	// jitter, GC pauses, and the natural push/pull oscillation
	// between the 50Hz producer and the ~43Hz consumer.
	queueCapacity = SamplesPerFrame * 12

	// queuePrefill is how many silence samples we seed the queue
	// with at startup so the consumer's first pull doesn't drain
	// the queue to zero. Without this cushion, the producer is
	// always exactly one push behind the consumer (they have equal
	// average rates but different periods), and every pull cycle
	// returns a partial buffer plus DC silence — audible as
	// stutter at the consumer's pull rate. Four frames give the
	// queue enough headroom that the discrete-event oscillation
	// never reaches the bottom.
	queuePrefill = SamplesPerFrame * 4
)

// AudioSystem handles audio output for the ZX Spectrum beeper and (on 128K+
// machines) the AY-3-8912 sound chip.
//
// The beeper input is event-driven: the ULA records every speaker bit
// toggle during the frame with the T-state at which it happened, and at
// end of frame generates a fresh batch of SamplesPerFrame mono samples
// that gets pushed via PushBeeperSamples. The oto playback callback
// pulls samples from the ring buffer; on underflow it holds the last
// sample (DC) instead of clicking.
//
// The AY chip is mixed in by the playback callback at audio-sample
// rate via AYSource.MixInto, since AY samples are generated by the
// chip's own internal counters and don't need event-time alignment.
type AudioSystem struct {
	context *oto.Context
	player  oto.Player
	reader  *audioReader

	// Beeper sample ring buffer.
	queueMu    sync.Mutex
	queue      [queueCapacity]int16
	queueHead  int   // next write position
	queueTail  int   // next read position
	queueSize  int   // number of samples currently in the buffer
	lastSample int16 // value to hold during underflow (DC, no clicks)

	// Optional AY-3-8912 source.
	ayMu sync.RWMutex
	ay   AYSource

	// WAV recording state. When recFile is non-nil the audio reader
	// appends each generated sample to the file as 16-bit mono PCM.
	recMu      sync.Mutex
	recFile    *os.File
	recSamples uint64
	recScratch []byte
}

// audioReader implements io.Reader on the oto playback goroutine.
type audioReader struct {
	audioSys  *AudioSystem
	buffer    []byte
	mixBuffer []int16
}

// New creates a new AudioSystem instance.
func New() (*AudioSystem, error) {
	ctx, ready, err := oto.NewContext(SampleRate, ChannelCount, oto.FormatSignedInt16LE)
	if err != nil {
		return nil, fmt.Errorf("failed to create audio context: %w", err)
	}
	<-ready

	as := &AudioSystem{context: ctx}
	as.reader = &audioReader{
		audioSys:  as,
		buffer:    make([]byte, BufferSize*ChannelCount*2),
		mixBuffer: make([]int16, BufferSize),
	}
	as.prefillSilence()
	as.player = ctx.NewPlayer(as.reader)
	return as, nil
}

// prefillSilence seeds the ring buffer with queuePrefill silent
// samples so the consumer's first few pulls are satisfied without
// draining the queue. See the queuePrefill doc comment for the rate-
// matching reasoning.
func (as *AudioSystem) prefillSilence() {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	as.queueHead = queuePrefill % queueCapacity
	as.queueTail = 0
	as.queueSize = queuePrefill
	for i := 0; i < queuePrefill; i++ {
		as.queue[i] = 0
	}
	as.lastSample = 0
}

// PushBeeperSamples enqueues a batch of mono beeper samples generated
// by the ULA at end of frame. The samples are consumed by the oto
// playback goroutine via Read. If the buffer would overflow (the
// playback goroutine is falling behind), the oldest samples are
// dropped — audio glitches are preferable to growing latency.
func (as *AudioSystem) PushBeeperSamples(samples []int16) {
	if len(samples) == 0 {
		return
	}
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	for _, s := range samples {
		as.queue[as.queueHead] = s
		as.queueHead = (as.queueHead + 1) % queueCapacity
		if as.queueSize == queueCapacity {
			// Buffer is full; advance tail to drop the oldest sample.
			as.queueTail = (as.queueTail + 1) % queueCapacity
		} else {
			as.queueSize++
		}
	}
}

// popBeeperSamples drains up to len(out) samples from the ring buffer
// into out. Any unfilled slots are held at lastSample (DC) so the
// audio output stays smooth across underruns instead of clicking.
// Returns the slice unchanged.
func (as *AudioSystem) popBeeperSamples(out []int16) {
	as.queueMu.Lock()
	defer as.queueMu.Unlock()
	n := 0
	for n < len(out) && as.queueSize > 0 {
		out[n] = as.queue[as.queueTail]
		as.queueTail = (as.queueTail + 1) % queueCapacity
		as.queueSize--
		n++
	}
	if n > 0 {
		as.lastSample = out[n-1]
	}
	for ; n < len(out); n++ {
		out[n] = as.lastSample
	}
}

// Read implements io.Reader for the audioReader. Pulls beeper samples
// from the ring buffer, mixes in any attached AY chip, then expands
// the mono mix to stereo for the oto sink.
func (ar *audioReader) Read(p []byte) (n int, err error) {
	bytesToRead := len(p)
	if bytesToRead > len(ar.buffer) {
		bytesToRead = len(ar.buffer)
	}
	samples := bytesToRead / (ChannelCount * 2)

	if cap(ar.mixBuffer) < samples {
		ar.mixBuffer = make([]int16, samples)
	}
	mixBuf := ar.mixBuffer[:samples]

	// Step 1: pull beeper samples from the ULA's ring buffer.
	ar.audioSys.popBeeperSamples(mixBuf)

	// Step 2: mix in the AY chip's output (it generates samples
	// from its own internal counters at audio rate).
	ar.audioSys.ayMu.RLock()
	ay := ar.audioSys.ay
	ar.audioSys.ayMu.RUnlock()
	if ay != nil {
		ay.MixInto(mixBuf)
	}

	// Step 3: WAV recording — append the mono mix before expansion.
	ar.audioSys.writeRecording(mixBuf)

	// Step 4: emit the mono mix as interleaved stereo bytes.
	for i := 0; i < samples; i++ {
		s := mixBuf[i]
		base := i * ChannelCount * 2
		ar.buffer[base] = byte(s)
		ar.buffer[base+1] = byte(s >> 8)
		ar.buffer[base+2] = byte(s)
		ar.buffer[base+3] = byte(s >> 8)
	}
	copy(p, ar.buffer[:bytesToRead])
	return bytesToRead, nil
}

// Start begins audio output.
func (as *AudioSystem) Start() error {
	as.player.Play()
	return nil
}

// Stop pauses audio output.
func (as *AudioSystem) Stop() {
	if as.player != nil {
		as.player.Pause()
	}
}

// SetAY attaches an AY-3-8912 source whose output will be mixed into
// the beeper stream. Pass nil to detach.
func (as *AudioSystem) SetAY(ay AYSource) {
	as.ayMu.Lock()
	defer as.ayMu.Unlock()
	as.ay = ay
}

// Close closes the audio system and releases resources.
func (as *AudioSystem) Close() error {
	as.Stop()
	_ = as.StopRecording()
	return nil
}

// Reset clears the beeper sample queue and re-seeds it with the
// startup silence cushion. Used on machine reset so the new session
// doesn't start with stale audio in the buffer AND immediately
// benefits from the same cushion that startup gets.
func (as *AudioSystem) Reset() {
	as.prefillSilence()
}

// StartRecording opens path for writing and begins capturing the mixed
// mono audio output as a 16-bit PCM WAV file at SampleRate. If a
// recording is already in progress it is finalised first.
func (as *AudioSystem) StartRecording(path string) error {
	if err := as.StopRecording(); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create wav file: %w", err)
	}
	if err := writeWavHeader(f, 0, 1, SampleRate, 16); err != nil {
		_ = f.Close()
		_ = os.Remove(path)
		return fmt.Errorf("write wav header: %w", err)
	}
	as.recMu.Lock()
	as.recFile = f
	as.recSamples = 0
	as.recMu.Unlock()
	return nil
}

// maxWavSamples is the largest number of mono 16-bit samples we can
// capture before either of the WAV header's uint32 size fields would
// overflow. About 13.6 hours at 44.1kHz; writeRecording stops
// appending past this point.
const maxWavSamples uint64 = (0xFFFFFFFF - 36) / 2

// StopRecording finalises any in-progress recording.
func (as *AudioSystem) StopRecording() error {
	as.recMu.Lock()
	f := as.recFile
	samples := as.recSamples
	as.recFile = nil
	as.recSamples = 0
	as.recMu.Unlock()
	if f == nil {
		return nil
	}
	if _, err := f.Seek(0, 0); err != nil {
		_ = f.Close()
		return err
	}
	if err := writeWavHeader(f, uint32(samples), 1, SampleRate, 16); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// IsRecording reports whether a WAV recording is currently in progress.
func (as *AudioSystem) IsRecording() bool {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	return as.recFile != nil
}

// writeRecording appends a mono sample buffer to the active WAV file.
func (as *AudioSystem) writeRecording(samples []int16) {
	as.recMu.Lock()
	defer as.recMu.Unlock()
	if as.recFile == nil {
		return
	}
	remaining := maxWavSamples - as.recSamples
	if remaining == 0 {
		return
	}
	n := uint64(len(samples))
	if n > remaining {
		n = remaining
		samples = samples[:n]
	}

	need := int(n) * 2
	if cap(as.recScratch) < need {
		as.recScratch = make([]byte, need)
	}
	buf := as.recScratch[:need]
	for i, s := range samples {
		binary.LittleEndian.PutUint16(buf[i*2:], uint16(s))
	}
	if _, err := as.recFile.Write(buf); err != nil {
		_ = as.recFile.Close()
		as.recFile = nil
		return
	}
	as.recSamples += n
}

// writeWavHeader writes a 44-byte canonical PCM WAV header.
func writeWavHeader(f *os.File, sampleCount uint32, channels uint16, sampleRate uint32, bitsPerSample uint16) error {
	byteRate := sampleRate * uint32(channels) * uint32(bitsPerSample) / 8
	blockAlign := channels * bitsPerSample / 8
	dataSize := sampleCount * uint32(blockAlign)
	riffSize := 36 + dataSize

	hdr := make([]byte, 44)
	copy(hdr[0:4], []byte("RIFF"))
	binary.LittleEndian.PutUint32(hdr[4:8], riffSize)
	copy(hdr[8:12], []byte("WAVE"))
	copy(hdr[12:16], []byte("fmt "))
	binary.LittleEndian.PutUint32(hdr[16:20], 16)
	binary.LittleEndian.PutUint16(hdr[20:22], 1)
	binary.LittleEndian.PutUint16(hdr[22:24], channels)
	binary.LittleEndian.PutUint32(hdr[24:28], sampleRate)
	binary.LittleEndian.PutUint32(hdr[28:32], byteRate)
	binary.LittleEndian.PutUint16(hdr[32:34], blockAlign)
	binary.LittleEndian.PutUint16(hdr[34:36], bitsPerSample)
	copy(hdr[36:40], []byte("data"))
	binary.LittleEndian.PutUint32(hdr[40:44], dataSize)

	_, err := f.Write(hdr)
	return err
}
