package plus3fdc

import (
	"bytes"
	"encoding/gob"
	"testing"
)

// The µPD765 is a device whose answer depends almost entirely on state the
// guest cannot read back. The main status register is four bits wide and the
// result bytes are gone the moment the CPU has taken them; what actually
// decides the next byte is the phase, the position inside the sector's data
// field, the running data CRC, the R in the command buffer already stepped part
// way through a multi-sector transfer, the per-drive head positions and PCNs,
// the seek results latched for a later SENSE INTERRUPT, and the Speedlock retry
// counter. None of that appears in any snapshot format.
//
// These tests are written as a replay property — capture, run a script,
// restore, run the same script, compare every byte the guest saw — rather than
// field by field, because a field-by-field test only checks the fields someone
// remembered to add.
//
// Each fixture stops the controller in a different mid-command state, because a
// field can only be shown to matter at a capture point where its value is both
// live and different from what the script leaves behind. Where a field cannot
// be reached that way, state.go says so rather than pretending.

// tape drives the FDC the way the CPU does, through the +3 port decode, and
// records everything the guest could see: every main-status byte and every data
// byte, in order.
type tape struct {
	t   *testing.T
	p   *Plus3FDC
	out []byte
}

func newTape(t *testing.T, p *Plus3FDC) *tape {
	t.Helper()
	return &tape{t: t, p: p}
}

// status reads the main status register at 0x2FFD.
func (tp *tape) status() byte {
	tp.t.Helper()
	v, ok := tp.p.HandlePortRead(0x2FFD)
	if !ok {
		tp.t.Fatal("status port 0x2FFD not decoded by the FDC")
	}
	tp.out = append(tp.out, v)
	return v
}

// data reads one byte from the data register at 0x3FFD.
func (tp *tape) data() byte {
	tp.t.Helper()
	v, ok := tp.p.HandlePortRead(0x3FFD)
	if !ok {
		tp.t.Fatal("data port 0x3FFD not decoded by the FDC")
	}
	tp.out = append(tp.out, v)
	return v
}

// cmd writes command, parameter or execution-phase bytes to 0x3FFD.
func (tp *tape) cmd(bs ...byte) {
	tp.t.Helper()
	for _, b := range bs {
		tp.p.HandlePortWrite(0x3FFD, b)
	}
}

// send feeds count execution-phase bytes generated by pat, which is a pure
// function of the byte's position in the transfer so that both runs of a script
// send exactly the same stream.
func (tp *tape) send(from, count int, pat func(int) byte) {
	tp.t.Helper()
	for i := from; i < from+count; i++ {
		tp.status()
		tp.cmd(pat(i))
	}
}

// drain takes bytes from the FDC for as long as it is offering them, which is
// what a +3DOS transfer loop does: poll RQM/DIO and read until the controller
// stops being busy or turns the direction round to want bytes back.
func (tp *tape) drain() {
	tp.t.Helper()
	for i := 0; i < 1<<16; i++ {
		st := tp.status()
		if st&msrCB == 0 || st&msrDIO == 0 {
			return
		}
		tp.data()
	}
	tp.t.Fatal("FDC never stopped offering bytes")
}

// readN takes exactly n bytes, for stopping part way through a transfer.
func (tp *tape) readN(n int) {
	tp.t.Helper()
	for i := 0; i < n; i++ {
		tp.status()
		tp.data()
	}
}

// seek moves drive 0 to the given cylinder and clears the interrupt it raises,
// which is what every fixture below needs before it can touch a track.
func (tp *tape) seek(cyl byte) {
	tp.t.Helper()
	tp.cmd(0x0F, 0x00, cyl)
	tp.drain()
	tp.cmd(0x08)
	tp.drain()
}

// replayProperty is the shape every test below shares: prime a controller into
// a mid-command state, capture it, run a script, restore the capture, run the
// same script again, and require the guest to have seen identical bytes.
func replayProperty(t *testing.T, what string, prime func(*testing.T) *Plus3FDC, script func(*testing.T, *Plus3FDC) []byte) {
	t.Helper()
	p := prime(t)

	st := p.SaveState()
	first := script(t, p)

	if err := p.LoadState(st); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	second := script(t, p)

	if !bytes.Equal(first, second) {
		t.Errorf("replay from a capture taken %s gave the CPU different bytes: "+
			"some part of the controller is not being captured%s", what, firstDiff(first, second))
	}
}

// patterns the scripts send. Both are pure functions of the byte's position,
// and neither ever produces 0xFF, which a SCAN would treat as "don't care".
func writePattern(i int) byte { return byte(i*7+3) &^ 0x80 }
func scanPattern(i int) byte  { return byte(i) &^ 0x80 }

// readSector2 is a single-sector READ DATA of sector 2 on cylinder 0 of drive 1
// — R equal to EOT, C=0, even H. That exact shape is what arms the Speedlock
// retry detector, so re-issuing it is a retry and the bytes come back mangled.
var readSector2 = []byte{0x46, 0x01, 0, 0, 2, 2, 2, 0x2A, 0xFF}

// --- mid-transfer -----------------------------------------------------------

// primedMidTransfer stops half way through the mangled retry read, with three
// seeks latched and never sensed, three different PCNs, and the transfer
// running on drive 1 with head 0 — neither of which is what the script below
// leaves selected when it finishes.
func primedMidTransfer(t *testing.T) *Plus3FDC {
	t.Helper()
	p := New()
	p.fdc.AttachDisk(0, loadTestDisk(t))
	p.fdc.AttachDisk(1, loadTestDisk(t))
	p.SetSpeedlockEnabled(true)

	tp := newTape(t, p)
	// Three seek-complete results latched and deliberately not sensed, on
	// three of the four logical units, so the capture carries pending
	// interrupt status and three distinct present-cylinder numbers.
	tp.cmd(0x07, 0x00)       // RECALIBRATE drive 0
	tp.cmd(0x07, 0x01)       // RECALIBRATE drive 1
	tp.cmd(0x0F, 0x02, 0x05) // SEEK unit 2 → cylinder 5

	// Arm the retry detector, then re-issue the same read. The second read is
	// the retry, so Speedlock mangling is live for the rest of the sector.
	tp.cmd(readSector2...)
	tp.drain()
	tp.cmd(readSector2...)
	tp.readN(100) // stop mid data field, past the offset<64 window
	return p
}

// driveTransferForward finishes the in-flight transfer, takes all three latched
// seek results, senses every unit, walks the track with READ ID, retries the
// protected sector, then seeks elsewhere and reads on the other head — so the
// recording depends on the transfer position, the command buffer, the selected
// unit and head, both seek latches, every PCN and head position, and the
// Speedlock counter.
func driveTransferForward(t *testing.T, p *Plus3FDC) []byte {
	t.Helper()
	tp := newTape(t, p)

	tp.drain() // finish the mangled sector and take its result bytes

	for i := 0; i < 4; i++ { // three latched seeks, then nothing pending
		tp.cmd(0x08)
		tp.drain()
	}
	for u := byte(0); u < 4; u++ { // TRACK 0 in ST3 depends on each PCN
		tp.cmd(0x04, u)
		tp.drain()
	}

	tp.cmd(0x4A, 0x01) // READ ID drive 1 — answer depends on the head position
	tp.drain()

	tp.cmd(readSector2...) // the protected sector once more
	tp.drain()

	tp.seek(3) // drive 0 → cylinder 3
	tp.cmd(0x4A, 0x00)
	tp.drain()

	// Multi-sector read on the other head. Every sector's first three bytes are
	// its own C, H and R, so the recording says which track was really under
	// the head. This also leaves unit 0 / head 1 selected, which is neither of
	// the values the capture holds.
	tp.cmd(0x46, 0x04, 3, 1, 1, 2, 3, 0x2A, 0xFF)
	tp.drain()
	return tp.out
}

func TestReplayingFromCapturedStateReproducesTheSameTransfer(t *testing.T) {
	replayProperty(t, "mid transfer", primedMidTransfer, driveTransferForward)
}

// The negative that gives the test above its teeth. A capture of only what the
// guest can read back — the ports — restores a controller that runs but does
// not resume.
func TestPortVisibleStateAloneIsNotEnoughToReproduceTheTransfer(t *testing.T) {
	p := primedMidTransfer(t)
	st := p.SaveState()
	want := driveTransferForward(t, p)

	// Rebuild from the ports alone: a fresh controller with the same disks
	// mounted, which is everything a port-level capture could know.
	q := New()
	q.fdc.AttachDisk(0, loadTestDisk(t))
	q.fdc.AttachDisk(1, loadTestDisk(t))
	q.SetSpeedlockEnabled(true)
	if got := driveTransferForward(t, q); bytes.Equal(want, got) {
		t.Skip("this transfer happens not to depend on hidden state; " +
			"the replay test above is the binding one")
	}

	// ...and the full capture does what the ports alone could not.
	if err := p.LoadState(st); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if got := driveTransferForward(t, p); !bytes.Equal(want, got) {
		t.Errorf("full state capture failed to reproduce the transfer it was taken from%s",
			firstDiff(want, got))
	}
}

// --- mid-result phase -------------------------------------------------------

// A result phase the CPU has only partly drained is state: the remaining bytes
// exist nowhere else once the command that produced them has finished.
func TestReplayingFromMidResultPhaseReproducesTheSameResultBytes(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(4)
		tp.cmd(0x4A, 0x00) // READ ID — seven result bytes
		tp.readN(3)        // three of them taken
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.drain() // the remaining four
		tp.cmd(0x04, 0x00)
		tp.drain() // SENSE DRIVE STATUS: a one-byte result over the buffer
		// Finish on a two-byte result, so the buffer, its length and the index
		// into it are all left different from the captured ones.
		tp.cmd(0x0F, 0x00, 0x06)
		tp.drain()
		tp.cmd(0x08)
		tp.drain()
		return tp.out
	}
	replayProperty(t, "mid result phase", prime, script)
}

// --- mid-command parameters -------------------------------------------------

// A command half way through its parameter bytes is a state the guest can
// resume into, and the parameters already sent are not readable back.
func TestReplayingFromMidCommandParametersReproducesTheSameResult(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(5)
		tp.cmd(0x46, 0x00, 5, 0, 4) // READ DATA: opcode and four of eight params
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.cmd(2, 5, 0x2A, 0xFF) // N, EOT, GPL, DTL
		tp.drain()
		return tp.out
	}
	replayProperty(t, "mid command parameters", prime, script)
}

// --- mid-write --------------------------------------------------------------

// A write caught mid-sector holds the CRC it has accumulated so far, and that
// CRC is written into the track when the sector fills. Resume with the wrong
// accumulator and the sector reads back as a CRC error ever after.
func TestReplayingFromMidWriteReproducesTheSameSectorAndCRC(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(5)
		// WRITE DATA across sectors 1 and 2 — 1024 bytes in all.
		tp.cmd(0x45, 0x00, 5, 0, 1, 2, 2, 0x2A, 0xFF)
		tp.send(0, 300, writePattern)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.send(300, 724, writePattern)
		tp.drain()
		// Read the two sectors back: the data bytes say what was written, and
		// the status bytes say whether the CRC the controller left behind
		// matches the data it left behind.
		tp.cmd(0x46, 0x00, 5, 0, 1, 2, 2, 0x2A, 0xFF)
		tp.drain()
		return tp.out
	}
	replayProperty(t, "mid write", prime, script)
}

// --- mid-read of a deleted sector -------------------------------------------

// A deleted data mark on a sector a plain READ DATA asked for stops the
// transfer at the end of that sector. The controller decided that when it found
// the sector, several hundred bytes before the transfer ends.
func TestReplayingFromMidReadOfDeletedSectorStopsInTheSamePlace(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(6)
		tp.cmd(0x49, 0x00, 6, 0, 1, 2, 1, 0x2A, 0xFF) // WRITE DELETED DATA, sector 1
		tp.send(0, 512, writePattern)
		tp.drain()
		// Plain READ DATA, SK=0, over sectors 1..3. Sector 1 now carries a
		// deleted mark, so the control-mark flag is set for the whole transfer.
		tp.cmd(0x46, 0x00, 6, 0, 1, 2, 3, 0x2A, 0xFF)
		tp.readN(100)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.drain() // must stop after sector 1, with CM in ST2
		tp.cmd(0x46, 0x00, 6, 0, 2, 2, 2, 0x2A, 0xFF)
		tp.drain() // an ordinary sector, leaving the flag clear
		return tp.out
	}
	replayProperty(t, "mid read of a deleted sector", prime, script)
}

// READ DELETED DATA with the skip bit set walks past sectors whose mark does
// not match. Which sectors those are is decided per sector, from flags latched
// when the command started.
func TestReplayingFromMidReadDeletedWithSkipSkipsTheSameSectors(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(7)
		tp.cmd(0x49, 0x00, 7, 0, 1, 2, 2, 0x2A, 0xFF) // deleted marks on sectors 1 and 2
		tp.send(0, 1024, writePattern)
		tp.drain()
		// READ DELETED DATA with SK=1 over sectors 1..3. Sector 3 is an
		// ordinary sector, so the skip bit decides whether the transfer ends in
		// data or in "no data".
		tp.cmd(0x6C, 0x00, 7, 0, 1, 2, 3, 0x2A, 0xFF)
		tp.readN(100)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.drain()
		// A plain read afterwards, so neither the wanted mark nor the skip bit
		// is left as the capture had it.
		tp.cmd(0x46, 0x00, 7, 0, 3, 2, 3, 0x2A, 0xFF)
		tp.drain()
		return tp.out
	}
	replayProperty(t, "mid read of deleted data with skip", prime, script)
}

// A cylinder mismatch is noticed when the sector is found and acted on when the
// sector ends, so it too spans the whole transfer.
func TestReplayingFromMidWrongCylinderReadStopsInTheSamePlace(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(8)
		// Ask for cylinder 0 with the head over cylinder 8: the sectors are
		// there, the cylinder in their ID fields is not the one requested.
		tp.cmd(0x46, 0x00, 0, 0, 1, 2, 3, 0x2A, 0xFF)
		tp.readN(100)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.drain() // must stop after sector 1, with WC in ST2
		tp.cmd(0x46, 0x00, 8, 0, 2, 2, 2, 0x2A, 0xFF)
		tp.drain() // the right cylinder this time
		return tp.out
	}
	replayProperty(t, "mid read of the wrong cylinder", prime, script)
}

// --- mid-scan ---------------------------------------------------------------

// A scan carries one bit that no port exposes: whether every byte compared so
// far has met the condition. It is set on the first mismatch and only read out
// when the sector ends.
func TestReplayingFromMidScanReportsTheSameVerdict(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(9)
		tp.cmd(0x45, 0x00, 9, 0, 1, 2, 1, 0x2A, 0xFF) // a known pattern to scan
		tp.send(0, 512, scanPattern)
		tp.drain()
		// SCAN EQUAL, first byte deliberately wrong: the verdict is already
		// decided, 511 bytes before the controller reports it.
		tp.cmd(0x51, 0x00, 9, 0, 1, 2, 1, 0x2A, 0xFF)
		tp.status()
		tp.cmd(scanPattern(0) + 1)
		tp.send(1, 99, scanPattern)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.send(100, 412, scanPattern)
		tp.drain() // must report "not satisfied"
		// A scan that does match, so the flag is left the other way round.
		tp.cmd(0x51, 0x00, 9, 0, 1, 2, 1, 0x2A, 0xFF)
		tp.send(0, 512, scanPattern)
		tp.drain()
		return tp.out
	}
	replayProperty(t, "mid scan", prime, script)
}

// --- mid-read-diagnostic ----------------------------------------------------

// READ DIAGNOSTIC compares the ID it was given against every sector on the
// track when the command starts, and reports the answer in the result phase a
// whole track later.
func TestReplayingFromMidReadDiagnosticReportsTheSameNoData(t *testing.T) {
	prime := func(t *testing.T) *Plus3FDC {
		t.Helper()
		p := New()
		p.fdc.AttachDisk(0, loadTestDisk(t))
		tp := newTape(t, p)
		tp.seek(10)
		// R=0x55 is on no sector of this track, so ND is already decided.
		tp.cmd(0x42, 0x00, 10, 0, 0x55, 2, 2, 0x2A, 0xFF)
		tp.readN(100)
		return p
	}
	script := func(t *testing.T, p *Plus3FDC) []byte {
		t.Helper()
		tp := newTape(t, p)
		tp.drain() // must report ND in ST1
		tp.cmd(0x42, 0x00, 10, 0, 1, 2, 2, 0x2A, 0xFF)
		tp.drain() // an ID that is on the track, so the flag ends up clear
		return tp.out
	}
	replayProperty(t, "mid read diagnostic", prime, script)
}

// --- mid-format -------------------------------------------------------------

// primedMidFormat stops part way through the CHRN stream of a FORMAT TRACK,
// with a staging track allocated and three of five sectors described.
func primedMidFormat(t *testing.T) *Plus3FDC {
	t.Helper()
	p := New()
	p.fdc.AttachDisk(0, loadTestDisk(t))

	tp := newTape(t, p)
	tp.seek(1)
	tp.cmd(0x4D, 0x00, 0x02, 0x05, 0x54, 0xAA) // N=2, 5 sectors, filler 0xAA
	for r := byte(1); r <= 3; r++ {
		tp.cmd(1, 0, r, 2)
	}
	return p
}

// driveFormatForward finishes the in-flight format, reads back the track it
// wrote and the untouched track next to it, then formats a different cylinder
// on the other head with a different geometry and filler — so the format
// parameters left behind differ from every captured one, and a format that
// commits to the wrong place is visible in the read-backs.
func driveFormatForward(t *testing.T, p *Plus3FDC) []byte {
	t.Helper()
	tp := newTape(t, p)

	for r := byte(4); r <= 5; r++ {
		tp.cmd(1, 0, r, 2)
	}
	tp.drain() // format result phase

	tp.cmd(0x4A, 0x00) // READ ID on the freshly formatted track
	tp.drain()
	tp.cmd(0x46, 0x00, 1, 0, 1, 2, 3, 0x2A, 0xFF) // read back sectors 1..3
	tp.drain()
	tp.cmd(0x46, 0x04, 1, 1, 1, 2, 2, 0x2A, 0xFF) // and head 1, which no format touched
	tp.drain()

	tp.seek(2)
	tp.cmd(0x46, 0x00, 2, 0, 1, 2, 2, 0x2A, 0xFF) // cylinder 2, still as the image had it
	tp.drain()

	// A second format, on the other head with a different geometry and filler.
	tp.cmd(0x4D, 0x04, 0x01, 0x03, 0x54, 0x5A)
	for r := byte(1); r <= 3; r++ {
		tp.cmd(2, 1, r, 1)
	}
	tp.drain()
	tp.cmd(0x46, 0x04, 2, 1, 1, 1, 3, 0x2A, 0xFF)
	tp.drain()
	return tp.out
}

// A FORMAT caught mid-stream holds a staging track and the CHRN bytes received
// so far, neither of which is on the disk yet and neither of which the guest
// can read back.
func TestReplayingFromMidFormatReproducesTheSameTrack(t *testing.T) {
	replayProperty(t, "mid format", primedMidFormat, driveFormatForward)
}

// --- capture hygiene --------------------------------------------------------

// A capture must not alias the live controller. The registry copies the blob
// too, but a device handing back a view of its own buffers is a bug worth
// catching here — the FDC holds a command buffer, a result buffer, a CHRN
// accumulator and a staging track, all of which keep being written as the
// controller runs.
func TestCaptureIsIndependentOfLaterChanges(t *testing.T) {
	p := primedMidFormat(t)

	st := p.SaveState()
	kept := append([]byte(nil), st...)

	driveFormatForward(t, p) // rewrites command, CHRN and staging buffers

	if !bytes.Equal(st, kept) {
		t.Errorf("the captured blob changed while the FDC carried on running: "+
			"SaveState handed back a view of live state%s", firstDiff(kept, st))
	}

	// And the blob still restores the state it was taken from.
	if err := p.LoadState(st); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if got := driveFormatForward(t, p); len(got) == 0 {
		t.Error("restored FDC produced nothing")
	}
}

func TestStateIDIsStable(t *testing.T) {
	if got := New().StateID(); got != "plus3fdc" {
		t.Errorf("StateID = %q, want %q: it is stored in state blobs and must not drift", got, "plus3fdc")
	}
}

func TestLoadStateRejectsRubbish(t *testing.T) {
	p := New()
	if err := p.LoadState([]byte{0xDE, 0xAD, 0xBE, 0xEF}); err == nil {
		t.Error("a malformed state blob must be reported, not half-applied")
	}
}

// Rejecting is not enough on its own: a refused blob must leave the controller
// exactly as it was, because a half-applied state runs and the caller believes
// the restore worked.
func TestRefusedLoadStateLeavesTheFDCUntouched(t *testing.T) {
	p := primedMidTransfer(t)
	st := p.SaveState()
	want := driveTransferForward(t, p)

	if err := p.LoadState(st); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	// A truncated capture decodes far enough to be tempting and then fails.
	if err := p.LoadState(st[:len(st)/2]); err == nil {
		t.Fatal("a truncated state blob must be reported, not half-applied")
	}
	if got := driveTransferForward(t, p); !bytes.Equal(want, got) {
		t.Errorf("a refused LoadState changed the controller: it was half-applied%s",
			firstDiff(want, got))
	}
}

// firstDiff describes where two recordings part company, which is far more
// useful than "not equal" when the recordings are kilobytes of sector data.
func firstDiff(a, b []byte) string {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return " (first difference at byte " + itoa(i) + ": " +
				hexByte(a[i]) + " vs " + hexByte(b[i]) + ")"
		}
	}
	if len(a) != len(b) {
		return " (lengths differ: " + itoa(len(a)) + " vs " + itoa(len(b)) + ")"
	}
	return ""
}

func itoa(v int) string {
	if v == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	return string(buf[i:])
}

func hexByte(b byte) string {
	const digits = "0123456789ABCDEF"
	return string([]byte{digits[b>>4], digits[b&0x0F]})
}

// --- round trip on the capture itself ---------------------------------------

// The replay properties above have a blind spot, and a mutation audit found
// it: four of the controller's field restores could be deleted with every one
// of those tests still passing.
//
// Two causes, and both matter. Some fields cannot reach the guest at all from
// where a capture can stop. readDataCRC is decided on the last byte of a
// sector and read out in the same call, so by the time the CPU can take a
// capture the flag only describes a transfer that has already finished, and
// every path that reads it again writes it first. Others do reach the guest,
// but the fixture never made them differ between capture and restore, so
// deleting the restore left them already correct: seekResult's latched ST0 is
// a pure function of the drive index and whether that drive is ready, so a
// fixture that seeks the same drives in the script it seeked in the prime
// re-derives the same four bytes; and the tail of resultBuf that a partly
// drained result phase still owes the CPU stays untouched by the one- and
// two-byte results the script left behind it.
//
// The fix is the one the AY needed: stop asserting on what the guest saw and
// assert on the capture. Drive the controller so EVERY captured field differs,
// restore, and re-capture. A field that is captured and not restored shows up
// as a different blob, whether or not any port could ever have shown it.

// primedEveryField stops the controller with every captured field holding a
// value the drive sequence below will move.
//
// The shape is: a working disk in each drive, three seeks latched, a deleted
// sector made and then re-read as a Speedlock retry so the mangled bytes leave
// a failed data CRC behind, a failed scan, a READ DIAGNOSTIC for an ID that is
// not on the track, and finally a FORMAT stopped part way through its CHRN
// stream. That last one is what makes the capture sit in execution phase with
// a staging track, three sector descriptions and no transfer in flight.
func primedEveryField(t *testing.T) *Plus3FDC {
	t.Helper()
	p := New()
	p.fdc.AttachDisk(0, loadTestDisk(t))
	p.fdc.AttachDisk(1, loadTestDisk(t))
	p.SetSpeedlockEnabled(true)
	tp := newTape(t, p)

	// Three seeks latched, unit 3 deliberately never seeked: seekResult[d] can
	// only ever hold zero or one ST0 value per drive, so leaving one drive
	// untouched here is the only way the drive sequence can move that array.
	tp.cmd(0x07, 0x00)       // RECALIBRATE drive 0
	tp.cmd(0x0F, 0x01, 0x09) // SEEK unit 1 → cylinder 9
	tp.cmd(0x0F, 0x02, 0x05) // SEEK unit 2 → cylinder 5
	tp.cmd(0x08)             // sense unit 0 only, so seekDone stays uneven
	tp.drain()

	// A deleted sector 2 on cylinder 0, which is the sector Speedlock's check
	// reads and therefore the only one the retry detector arms on.
	tp.cmd(0x49, 0x00, 0, 0, 2, 2, 2, 0x2A, 0xFF)
	tp.send(0, 512, writePattern)
	tp.drain()

	// A scan whose first byte is wrong, so the verdict is "not satisfied".
	tp.cmd(0x45, 0x00, 0, 0, 1, 2, 1, 0x2A, 0xFF)
	tp.send(0, 512, scanPattern)
	tp.drain()
	tp.cmd(0x51, 0x00, 0, 0, 1, 2, 1, 0x2A, 0xFF)
	tp.status()
	tp.cmd(scanPattern(0) + 1)
	tp.send(1, 511, scanPattern)
	tp.drain()

	// R=0x55 is on no sector of this track, which is the ND answer.
	tp.cmd(0x42, 0x00, 0, 0, 0x55, 2, 2, 0x2A, 0xFF)
	tp.drain()

	// READ DELETED DATA with SK over the deleted sector, issued twice. The
	// second is the retry: Speedlock mangling XORs bytes and folds them into
	// the running CRC a second time, so the sector ends with a data CRC error
	// the controller latches. That is the only capture point at which
	// readDataCRC is true.
	del2 := []byte{0x6C, 0x00, 0, 0, 2, 2, 2, 0x2A, 0xFF}
	tp.cmd(del2...)
	tp.drain()
	tp.cmd(del2...)
	tp.drain()

	// FORMAT cylinder 0, N=2, five sectors, filler 0xAA — three of the five
	// CHRN quads sent, so the staging track and the accumulator are both live.
	tp.cmd(0x4D, 0x00, 0x02, 0x05, 0x54, 0xAA)
	for r := byte(1); r <= 3; r++ {
		tp.cmd(0, 0, r, 2)
	}
	return p
}

// driveEverything moves every field the capture carries.
//
// Each step is here because one field needs it, and the guard test below
// fails if any of them stops working. The ordering is the load-bearing part:
// the read flags are all latched when a read command starts, so whichever read
// runs last decides six of them at once, and the values have to be picked so
// that read disagrees with the primed one on every single flag. That is why
// the last read is a plain READ DATA (SK clear, wanting a normal mark) of a
// deleted sector on a cylinder it did not ask for: the primed capture got
// there with READ DELETED DATA and SK set, over a sector on the cylinder it
// did ask for.
func driveEverything(t *testing.T, p *Plus3FDC) {
	t.Helper()
	tp := newTape(t, p)

	for r := byte(4); r <= 5; r++ { // finish the format and take its result
		tp.cmd(0, 0, r, 2)
	}
	tp.drain()

	for i := 0; i < 3; i++ { // clear the three latched seeks
		tp.cmd(0x08)
		tp.drain()
	}
	tp.cmd(0x0F, 0x03, 0x07) // SEEK unit 3 → 7: the drive the prime never moved
	tp.cmd(0x0F, 0x01, 0x03) // SEEK unit 1 → 3, which is where the format goes

	// A second format, on the other drive and the other head, with a different
	// geometry and filler, run to completion so nothing is left staging. N=1
	// also gives the read below a 256-byte sector, which is what makes the
	// transfer offset differ from the primed 512.
	tp.cmd(0x4D, 0x05, 0x01, 0x03, 0x54, 0x5A)
	for r := byte(1); r <= 3; r++ {
		tp.cmd(3, 1, r, 1)
	}
	tp.drain()

	tp.cmd(0x49, 0x05, 3, 1, 1, 1, 1, 0x2A, 0xFF) // deleted mark on sector 1
	tp.send(0, 256, writePattern)
	tp.drain()

	// A scan that does match, so the verdict lands the other way round.
	tp.cmd(0x45, 0x05, 3, 1, 2, 1, 2, 0x2A, 0xFF)
	tp.send(0, 256, scanPattern)
	tp.drain()
	tp.cmd(0x51, 0x05, 3, 1, 2, 1, 2, 0x2A, 0xFF)
	tp.send(0, 256, scanPattern)
	tp.drain()

	// A READ DIAGNOSTIC for an ID that IS on the track, so ND ends up clear.
	tp.cmd(0x42, 0x05, 3, 1, 1, 1, 1, 0x2A, 0xFF)
	tp.drain()

	// The read that decides six flags at once: plain READ DATA, SK clear,
	// over the deleted sector, asking for cylinder 9 while the head is on 3.
	// It is also not the Speedlock pattern, so the retry counter and the last
	// sector ID both fall back to zero.
	tp.cmd(0x46, 0x05, 9, 1, 1, 1, 1, 0x2A, 0xFF)
	tp.drain()

	// Stop one byte into a two-byte result, so the phase, the result length
	// and the index into it are all different from the captured ones and the
	// buffer still owes the CPU a byte.
	tp.cmd(0x08)
	tp.readN(1)
}

func TestEveryCapturedFieldSurvivesARoundTrip(t *testing.T) {
	p := primedEveryField(t)
	want := p.SaveState()

	driveEverything(t, p)
	if bytes.Equal(p.SaveState(), want) {
		t.Fatal("the drive sequence changed nothing, so this test cannot detect a lost restore")
	}

	if err := p.LoadState(want); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if got := p.SaveState(); !bytes.Equal(got, want) {
		t.Errorf("re-capturing after a restore did not reproduce the captured state: "+
			"some field is captured but not restored%s", firstDiff(want, got))
	}
}

// The guard the test above depends on. A score is bounded by what the fixture
// moves, so if a later change retunes the drive sequence and a field stops
// differing, the round trip silently stops covering it — which is exactly how
// four restores survived deletion before this existed.
func TestTheDriveSequenceChangesEveryCapturedField(t *testing.T) {
	p := primedEveryField(t)
	before := decodeStateForTest(t, p.SaveState())
	driveEverything(t, p)
	after := decodeStateForTest(t, p.SaveState())

	for _, f := range []struct {
		name string
		same bool
	}{
		{"Phase", before.Phase == after.Phase},
		{"Cmd", before.Cmd == after.Cmd},
		{"CmdBuf", before.CmdBuf == after.CmdBuf},
		{"CmdLen", before.CmdLen == after.CmdLen},
		{"ResultBuf", before.ResultBuf == after.ResultBuf},
		{"ResultLen", before.ResultLen == after.ResultLen},
		{"ResultIdx", before.ResultIdx == after.ResultIdx},
		{"IOPos", before.IOPos == after.IOPos},
		{"IOEnd", before.IOEnd == after.IOEnd},
		{"IOCRC", before.IOCRC == after.IOCRC},
		{"IODataOffset", before.IODataOffset == after.IODataOffset},
		{"ReadCM", before.ReadCM == after.ReadCM},
		{"ReadDataCRC", before.ReadDataCRC == after.ReadDataCRC},
		{"ReadWrongCyl", before.ReadWrongCyl == after.ReadWrongCyl},
		{"ReadDiagNoID", before.ReadDiagNoID == after.ReadDiagNoID},
		{"ReadWantDeleted", before.ReadWantDeleted == after.ReadWantDeleted},
		{"ReadSK", before.ReadSK == after.ReadSK},
		{"ScanMatch", before.ScanMatch == after.ScanMatch},
		{"LastSectorID", before.LastSectorID == after.LastSectorID},
		{"SpeedlockCounter", before.SpeedlockCounter == after.SpeedlockCounter},
		{"FormatActive", before.FormatActive == after.FormatActive},
		{"FormatStaging", stagingEqual(before.FormatStaging, after.FormatStaging)},
		{"FormatCyl", before.FormatCyl == after.FormatCyl},
		{"FormatHead", before.FormatHead == after.FormatHead},
		{"FormatN", before.FormatN == after.FormatN},
		{"FormatNumSec", before.FormatNumSec == after.FormatNumSec},
		{"FormatFiller", before.FormatFiller == after.FormatFiller},
		{"FormatCHRN", bytes.Equal(before.FormatCHRN, after.FormatCHRN)},
		{"HeadPos", before.HeadPos == after.HeadPos},
		{"PCN", before.PCN == after.PCN},
		{"SeekDone", before.SeekDone == after.SeekDone},
		{"SeekResult", before.SeekResult == after.SeekResult},
		{"US", before.US == after.US},
		{"HD", before.HD == after.HD},
		// IOActive is deliberately absent: a transfer and a format cannot both
		// be in flight, and this capture is taken mid-format.
		// TestARoundTripBetweenATransferAndAFormat moves it, in both
		// directions, because each direction clears a different pointer.
		//
		// FormatFail is deliberately absent too, and unlike every other field
		// here that is not something a better fixture could fix. It is set and
		// cleared inside one call to execWriteIDByte — the last CHRN byte
		// builds the track, reports ST1.ND if the layout did not fit, and
		// clears the flag again before the call returns — and that call holds
		// the controller's mutex throughout. No capture, from the CPU or from
		// the UI thread, can be taken while it is true. It is a local variable
		// living in a struct field, and it is captured only because the
		// capture is a complete one; nothing can move it.
	} {
		if f.same {
			t.Errorf("%s is unchanged by the drive sequence, so a lost restore of it "+
				"would go undetected", f.name)
		}
	}
}

// A transfer and a format are the controller's two mutually exclusive
// execution phases, and each holds a live pointer that no encoding carries:
// ioTrack for the transfer, formatStaging and formatDisk for the format. Both
// are re-resolved on restore from the flag that says whether they were live,
// which means a restore has to CLEAR the one the captured state did not have.
// Neither direction can be shown by a fixture that only ever runs one way, so
// this runs both.
func TestARoundTripBetweenATransferAndAFormat(t *testing.T) {
	p := primedMidFormat(t)
	midFormat := p.SaveState()

	tp := newTape(t, p)
	for r := byte(4); r <= 5; r++ { // finish the format
		tp.cmd(1, 0, r, 2)
	}
	tp.drain()
	tp.cmd(0x46, 0x00, 1, 0, 1, 2, 3, 0x2A, 0xFF) // and stop inside a read
	tp.readN(100)
	midTransfer := p.SaveState()

	// A capture with no transfer in flight, restored over one that has a
	// track under the head, must leave nothing behind.
	if err := p.LoadState(midFormat); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if got := p.SaveState(); !bytes.Equal(got, midFormat) {
		t.Errorf("restoring a mid-format capture over a live transfer left the transfer "+
			"in place%s", firstDiff(midFormat, got))
	}

	// And the other way: a capture with no format in flight, restored over a
	// staging track and the disk it was going to be written to.
	if err := p.LoadState(midTransfer); err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if got := p.SaveState(); !bytes.Equal(got, midTransfer) {
		t.Errorf("restoring a mid-transfer capture over a live format left the format "+
			"in place%s", firstDiff(midTransfer, got))
	}
}

func decodeStateForTest(t *testing.T, b []byte) fdcState {
	t.Helper()
	var s fdcState
	if err := gob.NewDecoder(bytes.NewReader(b)).Decode(&s); err != nil {
		t.Fatalf("decoding state: %v", err)
	}
	return s
}

// stagingEqual compares two flattened FORMAT staging tracks. trackState holds
// slices, so it is not comparable with ==.
func stagingEqual(a, b trackState) bool {
	return a.C == b.C && a.H == b.H && a.N == b.N && a.Filler == b.Filler &&
		a.BPT == b.BPT && bytes.Equal(a.Data, b.Data) &&
		bytes.Equal(a.Clocks, b.Clocks) && bytes.Equal(a.Weak, b.Weak)
}
